name: HerokuDeployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy
        run: echo build start
      - name: Publish to heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          APP_NAME: ${{'semantic-similarity-api'}}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
          echo test, and deploy your project.
